### ISSUE TITLE
Tizonia doesn't recognize sub (nested) folders.

### ISSUE THREAD

**Issue by globetrotterdk** [tizonia/tizonia.github.com#1]
Most CD ripper programs rip within a newly created folder representing the CD's name and artist, yet Tizonia appears to be oblivious to all nested folders in ~/Music.

**Comment by tizonia** [comment]
@globetrotterdk : Thanks for reporting. 
Since this is the website's repo. Could you please report this on the main repo's issue tracker (https://github.com/tizonia/tizonia-openmax-il)?. Please add details of the command line used (e.g. did you use the --recurse flag?)

Thanks
